sudo: required
services:
  - docker

before_install:
  - docker build -t georgeadmintools/docker-react -f Dockerfile.dev .

script:
  - docker run georgeadmintools/docker-react npm run test -- --coverage
